### ISSUE TITLE
1.5/1.7 - Intentionally not listed in supportability metrics for 1.5+ Coroutines versions?

### ISSUE THREAD

**Issue by MT-Jacobs** [newrelic/newrelic-java-kotlin-coroutines#29]
I want to make sure that I've correctly set up new-relic-java-coroutines in my Kotlin application's extensions directory for the New Relic Agent.

I performed the verification steps [listed in the README](https://github.com/newrelic/newrelic-java-kotlin-coroutines/tree/main?tab=readme-ov-file#verification), checking for:

`supportability/weaveinstrumentation/loaded/com.newrelic.instrumentation.labs.kotlin-coroutines` and
`supportability/weaveinstrumentation/skipped/com.newrelic.instrumentation.labs.kotlin-coroutines`.

Here's what I see for my application using kotlin coroutines 1.7.3:

<img width="369" alt="morpheus-kotlin-producer-matt___New_Relic" src="https://github.com/user-attachments/assets/cb979d88-8228-4c2b-bf29-7932085df312">

and here's what's skipped:

<img width="367" alt="morpheus-kotlin-producer-matt___New_Relic" src="https://github.com/user-attachments/assets/1679249c-797e-4d67-8ac6-affaaab3a0cb">

So from what I can tell, 1.4 is used, but 1.5 and 1.7 were _not_ skipped. So which is it exactly? Did I run into a case where I'm on an older release than I should be?

**Comment by dhilpipre** [comment]
So  version 1.4 should not be able to load in an environment that is using any version 1.5 or beyond.  Instrumentation in the New Relic Java Agent is based upon method signatures and if the signature does not match then it is skipped.  Because of a change to method signature from 1.4 changed in 1.5 and beyond, it shouldn't load.  This is the case in all of our test instances. 
As to 1.7 not showing up, it may be related to the Java version you are using, it appears that the extension for 1.7 was compiled using Java 9 and if you're running Java 8, 1.7 will not show up as loaded or skipped.  Looking into if it is necessary not to compile 1.7 to Java 8.
Not sure why 1.5 does not show up.
Can you send me the following:

1. Version of Java you are using.
2. Verify that only Coroutines 1.7 is on the classpath

Also if you can do the following it may have to debug the problem:
In newrelic.yml, set the log_level to finest.
Add the following system property to the startup: -Dnewrelic.debug=true
Recommend removing any logs in the logs directory of the New Relic Agent so we have a clean log file
Start the application and look for the following which tells us loading and skipping
Skipping instrumentation module 
validated classloader 

In particular, we're interested in module is like Kotlin-Coroutines_1.x

**Comment by MT-Jacobs** [comment]
I tried to reproduce this last week based on your instructions, starting with fresh downloads of the extensions and agent, and sure enough, I can no longer reproduce.

Ultimately though, I was trying to figure out how the agent determines what version to use (and how to triage it) since I couldn't find it in the code - it sounds like the answer is in matching the method signatures.

I'll go ahead and close this out and make sure to start with a sharable reproducible build next time. Thank you for your help!
